Repository tryber/sd-01-week13-project-frontend-online-store, pull requests merged in 2019-12, with the labels that each got.

#2 Add wireframes to repository
  wireframes/bonus_02.1.png
  wireframes/bonus_02.2.png
  wireframes/bonus_04.png
  wireframes/bonus_07.1.png
  wireframes/bonus_07.2.png
  wireframes/bonus_08.png
  wireframes/card_01.png
  wireframes/card_02.1.png
  wireframes/card_02.2.png
  wireframes/card_03.png
  wireframes/card_04.1.png
  wireframes/card_04.2.png
  wireframes/card_05.1.png
  wireframes/card_05.2.png
  wireframes/card_06.png
  wireframes/card_07.png
  wireframes/card_08.1.png
  wireframes/card_08.2.png
  wireframes/card_09.png
  wireframes/card_10.png
  wireframes/card_11.png
  wireframes/card_12.png
Labels: documentation, enhancement

#3 Change project README
  README.md
Labels: documentation, enhancement

#4 Hotfix: Project README
  README.md
Labels: bug, documentation, enhancement

#5 Refactor wireframes
  wireframes/bonus_02.1.png
  wireframes/bonus_04.png
  wireframes/bonus_07.1.png
  wireframes/bonus_07.2.png
  wireframes/bonus_08.png
  wireframes/card_03.png
  wireframes/card_04.1.png
  wireframes/card_04.2.png
  wireframes/card_05.1.png
  wireframes/card_05.2.png
  wireframes/card_10.png
  wireframes/card_12.png
Labels: enhancement

#20 Att master
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/CartButton.jsx
  src/components/CartShopping.jsx
  src/components/CategoryBar.css
  src/components/CategoryBar.jsx
  src/components/OnlineStore.jsx
  src/components/Product.jsx
  src/components/ProductList.css
  src/components/ProductList.jsx
  src/components/SearchBar.jsx
  src/components/cartShopping.css
  src/icons/back.svg
  src/icons/cart.jpg
  src/icons/emptyBox.png
  src/index.css
  src/index.js
  src/logo.svg
  src/serviceWorker.js
Labels: code-review

#22 realizando bonus para exibir o frete gratis
  src/components/Product.jsx
  src/components/ProductList.jsx
Labels: code-review

#21 Add to cart from listing - In progress
  package.json
  src/components/CartButton.jsx
  src/components/CartShopping.jsx
  src/components/CategoryBar.jsx
  src/components/OnlineStore.jsx
  src/components/Product.jsx
  src/components/ProductList.jsx
  src/components/cartShopping.css
Labels: code-review

#30 arrumando bugs no componente Avaliation
  src/components/Avaliation.jsx
  src/components/CreateAvaliation.jsx
  src/components/Product.jsx
Labels: code-review

#32 estilizando componente product
  src/components/Avaliation.jsx
  src/components/CreateAvaliation.jsx
  src/components/Product.jsx
  src/components/avaliation.css
  src/components/createAvaliation.css
  src/components/product.css
Labels: code-review

#33 Botao mostra quantidade de produtos no carrinho
  package-lock.json
  package.json
  src/components/AddToCartButton.jsx
  src/components/Avaliation.jsx
  src/components/ButtonOrderedBy.jsx
  src/components/CartButton.jsx
  src/components/CartShopping.jsx
  src/components/EachProduct.css
  src/components/EachProduct.jsx
  src/components/OnlineStore.jsx
  src/components/ProductList.css
  src/components/ProductList.jsx
  src/components/QuantityChanger.css
  src/components/QuantityChanger.jsx
  src/components/ShoppingProduct.css
  src/components/ShoppingProduct.jsx
  src/components/cartShopping.css
  src/icons/minus_icon.png
  src/icons/minus_icon.svg
  src/icons/plus_icon.png
  src/icons/plus_icon.svg
Labels: code-review

#36 Estilização da MainPage
  src/components/CategoryBar.css
  src/components/OnlineStore.jsx
  src/components/SearchBar.jsx
  src/components/mainPage.css
Labels: code-review

#38 Descatar Produto
  src/components/EachProduct.jsx
Labels: code-review

#39 Estilo css
  src/components/CartButton.jsx
  src/components/CategoryBar.css
  src/components/OnlineStore.jsx
  src/components/ProductList.css
  src/components/ProductList.jsx
  src/components/SearchBar.jsx
  src/components/cartButton.css
  src/components/mainPage.css
Labels: code-review

#43 Add Files
  src/App.css
  src/components/AddToCartButton.jsx
  src/components/EachProduct.jsx
  src/components/addcartbutton.css
  src/components/cartButton.css
  src/components/mainPage.css
Labels: code-review

#47 Done
  src/components/EachProduct.jsx
Labels: code-review

#54 Category Bar Changes
  src/components/CategoryBar.css
  src/components/CategoryBar.jsx
Labels: code-review

#55 Adjusting product list css
  src/components/CategoryBar.css
  src/components/ProductList.css
Labels: code-review
